server:
  port: 1996
spring:
  data:
    elasticsearch:
      # elastic的节点名字
      cluster-name: docker-cluster
      # elastic的节点IP地址
      cluster-nodes: 49.233.164.73:9300
#日志打印
logging:
  level:
    root: info # root日志以info形式输出
    com.zshuai: debug #com.zshuai包下面的日志全部以debug级别输出
  file: log/es.log