server:
  port: 1997
spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    host: 49.233.164.73
    port: 5672
    username: zshuai
    password: zshuai
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /zshuai
    #消息确认配置项

    publisher-confirms: true #确认消息已经发送到交换机
    publisher-returns: true  # 确认消息发送到队列