server:
  port: 1998
spring:
  #给项目来个名字
  application:
    name: rabbitmq-consumer
  #配置rabbitMq 服务器
  rabbitmq:
    host: 49.233.164.73
    port: 5672
    username: zshuai
    password: zshuai
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /zshuai